PRETRAINED_EMBEDDING = "pre-trained",
LOCRAINED_EMBEDDING = "locally-trained",
ONE_HOT_EMBEDDING = "one-hot"
EMBEDDING_TYPES = [PRETRAINED_EMBEDDING, LOCRAINED_EMBEDDING, ONE_HOT_EMBEDDING]


NUMERIC = "numeric"
CATEGORICAL = "categorical"
TEXT = "text"
DATA_TYPES = [NUMERIC, CATEGORICAL, TEXT]
