dtype_dict = {'titanic':[  
                        'categorical',
                        'text',
                        'categorical',
                        'numeric',
                        'categorical',
                        'categorical',
                        'text',
                        'numeric',
                        'text',
                        'categorical',
                      ],
              'marketing':[  
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                      ],
               'adult':[  
                        'numeric',
                        'categorical',
                        'numeric',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'numeric',
                        'numeric',
                        'numeric',
                        'categorical',
                      ],
               'student-mat':[  
                       'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                      ],
               'university': [  
                        'text',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'text',
                      ],
                'restaurant': [
                        'text',
                        'text',
                        'categorical',
                        'categorical',
                        'text',
                        'text',
                        'text',
                        'text',
                        'categorical',
                        'text',
                ],
                'ttt': ['categorical']*9,
                'ttt2': ['categorical']*18,
                'enron': ['numeric']*5116,
                'wine': ['numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        'numeric',
                        ],
                'letter': ['categorical']*17,
                'creditcard': ['numeric',
                            'categorical',
                            'categorical',
                            'categorical',
                            'numeric',
                            'categorical',
                            'categorical',
                            'categorical',
                            'categorical',
                            'categorical',
                            'categorical',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'numeric',
                            'categorical',
                        ],
                'hospital':[
                        'categorical',
                        'text',
                        'text',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'categorical',
                        'text',
                        'numeric',
                        'numeric',
                        'categorical',
                    ],
                'sensor': ['numeric']*7,
                'HTRU2': ['numeric']*8,
                'synthetic_r2': ['numeric']*10,
                'synthetic_r4': ['numeric']*10,
                'synthetic_r6': ['numeric']*10,
                'synthetic_r8': ['numeric']*10,
                'synthetic_r10': ['numeric']*10,

}

input_dim_dict = {'titanic': 64, 'marketing': 64, 'adult': 64, 'student-mat': 64, 
                'university': 80, 'restaurant': 64, 'ttt': 8, 'ttt2': 8, 'enron': 4, 
                'wine': 8, 'letter': 32, 'creditcard': 16, 'hospital': 64, 'sensor': 8, 'HTRU2': 8,
                'synthetic_r2': 8, 'synthetic_r4': 8, 'synthetic_r6': 8, 'synthetic_r8': 8, 'synthetic_r10': 8,}

batch_size_dict = {'titanic': 100, 'marketing': 1000, 'adult': 2000, 'student-mat': 100, 
                'university': 100, 'restaurant': 1000, 'ttt': 1000, 'ttt2': 1000, 'enron': 1000,
                'wine': 1000, 'letter': 1000, 'creditcard': 2000, 'hospital': 200, 'sensor': 1000, 'HTRU2': 1000}

resample_dict = {'titanic': False, 'marketing': False, 'adult': True, 'student-mat': False, 
                'university': False, 'restaurant': False, 'ttt': False, 'ttt2': False, 'enron': True,
                'wine': False,  'letter': False, 'creditcard': False, 'hospital': False, 'sensor': True, 'HTRU2': True,
                'synthetic_r2': False, 'synthetic_r4': False, 'synthetic_r6': False, 'synthetic_r8': False, 'synthetic_r10': False}
